worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    access_log  /var/log/nginx/access.log;
    error_log   /var/log/nginx/error.log warn;

    sendfile        on;
    keepalive_timeout  65;

    # Włączenie kompresji dla szybszego ładowania kodu Reacta
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        listen 80;
        listen [::]:80;
        server_name localhost;

        # Serwowanie plików statycznych React / Vite
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            # Zapobiega błędom 404 po odświeżeniu podstron React Routera
            try_files $uri $uri/ /index.html;
        }

        # Szybkie Reverse Proxy łączące się bezpośrednio z Twoim wewnętrznym backendem ACA
       # POPRAWIONE REVERSE PROXY W NGINX
        location /api/ {
            # Kończymy adres bezpośrednio na nazwie domeny, bez dodatkowego /api/ na końcu
            proxy_pass http://lakicraft-backend.internal.nicebeach-823a1a81.northeurope.azurecontainerapps.io;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_connect_timeout 15s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }