# 1. Konfiguracja Prometheus
prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

# 2. Wyłączamy Alertmanager - Grafana będzie wysyłać maile samodzielnie
alertmanager:
  enabled: false

# 3. Konfiguracja Grafany
grafana:
  enabled: true
  assertNoLeakedSecrets: false
  adminPassword: "MojeSilneHasloDevOps2026!"
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
  
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchInNamespaces: ["monitoring", "default"]
  
  grafana.ini:
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: mateusz.czarnik.1989@gmail.com
      password: "xfrimraqzcwcujzu"
      skip_verify: true
      from_address: mateusz.czarnik.1989@gmail.com
      from_name: Grafana
    unified_alerting:
      enabled: true
    alerting:
      enabled: false

# 4. Pozostałe komponenty
nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true