apiVersion: apps/v1
kind: Deployment
metadata:
  name: lakicraft-backend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lakicraft-backend
  template:
    metadata:
      labels:
        app: lakicraft-backend
    spec:
      containers:
        - name: backend
          image: matysz21/lakicraft-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PGHOST
              value: "postgres"
            - name: PGDATABASE
              value: "lakicraft_prod"
            - name: PGUSER
              value: "lakicraft_user"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: lakicraft-secrets
                  key: db-password
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lakicraft-secrets
                  key: mail-password