apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lakicraft-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # Ta linijka nakazuje cert-managerowi automatyczne pobranie certyfikatu Let's Encrypt
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Wymusza automatyczne przekierowanie z nieszyfrowanego http:// na bezpieczne https://
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - lakicraft.pl
        - www.lakicraft.pl
      secretName: lakicraft-tls-secret # Tu cert-manager automatycznie zapisze klucze SSL
  rules:
    # REGUŁY DLA GŁÓWNEJ DOMENY
    - host: lakicraft.pl
      http:
        paths:
          # Wszystko z prefiksem /api trafia do Spring Boota
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lakicraft-app-backend # Poprawiona nazwa działającego serwisu!
                port:
                  number: 8080
          # Cała reszta ruchu (strona główna, skrypty) trafia do Reacta
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lakicraft-frontend-service
                port:
                  number: 80

    # REGUŁY DLA DOMENY Z WWW (żeby działały oba adresy)
    - host: www.lakicraft.pl
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: lakicraft-app-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lakicraft-frontend-service
                port:
                  number: 80